version: "2"
services:
  # oh yeah it is that file...
  api:
    hostname: elixirgarden-api
    ports:
      - 4000:4000
    build:
      context: .
    links:
      - "postgres"
      - "rabbitmq:elixirgarden-rabbitmq"
    volumes:
      - ".:/home/app"
  postgres:
    build: ./docker/elixirgarden-postgres
    environment:
      - DB_NAME=elixirgarden_api_dev,elixirgarden_api_test,elixirgarden_api_production
      - DB_USER=elixirgarden
      - DB_PASS=elixirgarden

    ports:
      - 5432:5432
  rabbitmq:
    build: "./docker/elixirgarden-rabbitmq"
    hostname: "elixirgarden-rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
    labels:
      NAME: "elixirgarden-rabbitmq"
    volumes:
     - "/data/log"
     - "/data/mnesia"
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
