version: "2"
services:
  # oh yeah it is that file...
  web:
    image: ianneub/swagger-ui
    environment:
      - "URL=http://127.0.0.1:4001/api/swagger"
    ports:
      - '90:80'
  api:
    hostname: elixirgarden-api
    ports:
      - 4001:4000
    build:
      context: .
    links:
      - "postgres:postgres"
    volumes:
      - ".:/home/app"
  postgres:
    build: ./docker/elixirgarden-postgres
    environment:
      - DB_NAME=elixirgarden_api_dev,elixirgarden_api_test,elixirgarden_api_production
      - DB_USER=elixirgarden
      - DB_PASS=elixirgarden

    ports:
      - 5432:5432
    hostname: elixirgarden-postgres
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
