version: "2"
services:
  # oh yeah it is that file...
  web:
    image: ianneub/swagger-ui
    environment:
      - "URL=http://127.0.0.1:4001/api/swagger"
    ports:
      - '80:80'
  api:
    hostname: elixirgarden-api
    ports:
      - 4001:4000
    build:
      context: .
    links:
      - "postgres:postgres"
    volumes:
      - ".:/home/app"
  postgres:
    build: ./docker/elixirgarden-postgres
    environment:
      - DB_NAME=elixirgarden-dev,elixirgarden-test,elixirgarden-production
      - DB_USER=elixirgarden
      - DB_PASS=elixirgarden
    ports:
      - 5432:5432
    hostname: elixirgarden-postgres
